### ISSUE TITLE
missing tshek in a replacement for Old Tibetan?

### ISSUE THREAD

**Issue by eroux** [tibetan-nlp/tibcg3#3]
Hi, I'm porting the Old Tibetan normalization rules to the [Lucene analyzer](https://github.com/buda-base/lucene-bo/) and I have a few questions:
- I'd like to cite your work on this, what would be the best way to do so?
- I think line 51 should be `"<སྩོགསྟེ$1>"v "སྩོགས་སྟེ$1"v σ` instead of `"<སྩོགསྟེ$1>"v "སྩོགསསྟེ$1"v σ` (a tshek is missing)

**Comment by eroux** [comment]
I'm also a bit confused by these two rules:

```
SUBSTITUTE ("ཅེད་པོ((འི|ར|ས)?་)"r) ("ཅེན་པོ$1"v) TARGET (σ);
...
SUBSTITUTE ("ཅེན་") ("ཆེན་") TARGET (σ) (1 ("(པོ|ཕོ)(འི|ས|ར)?་?"r));
```

doesn't it mean that `ཅེད་པོ` will always be replaced with `ཆེན་པོ` ?

**Comment by heacu** [comment]
thanks for noticing the missing tsheg, @eroux . i have fixed it.

as for citing the work, you could cite the repo, or this paper (https://ep.liu.se/konferensartikel.aspx?series=&issue=168&Article_No=3), or maybe @FChrispz can mention other articles.

**Comment by eroux** [comment]
excellent, thanks a lot! what do you think of the ཅེད་པོ thing?

**Comment by FChrispz** [comment]
@eroux hi and thanks for spotting the missing thseg. As @heacu suggested you can cite our article on Cg3 grammar. As for the second question: we want all the possible OT variants to be normalized to ཆེན་པོ་ - am I reading your question correctly?

**Comment by eroux** [comment]
oh ok that's good, I'm just thinking it might be a bit more straightforward (I mean easier to understand) to write

```
SUBSTITUTE ("ཅེ(ད|ན)་(པོ|ཕོ)((འི|ར|ས)?་)"r) ("ཆེན་པོ$2"v) TARGET (σ);
```

but it's a small detail, I just wanted to check that it wasn't a bug, thanks!

**Comment by FChrispz** [comment]
that's a good suggestion, thanks! It looks cleaner.

**Comment by eroux** [comment]
Sorry to bother you again but here's another puzzlement I have, in:

```
SPLITCOHORT (
  "<$1>"v "$1ག་"v σ
  "<$2>"v "ག$4"v σ
)("<(.)((\\u0F42)([\\u0F72\\u0F80]་?))>"r)
```

that means you're also going to split the following:
-  `དགི*` -> `དག་གི*`
-  `བགི*` -> `བག་གི*`
-  `མགི*` -> `མག་གི*`
-  `འགི*` -> `འག་གི*`

but in these 4 cases it can be analyzed as
- prefix (ད, བ, མ or འ)
- main letter ga
- gigu

instead of the contraction... so maybe

```
SPLITCOHORT (
  "<$1>"v "$1ག་"v σ
  "<$2>"v "ག$4"v σ
)("<([^དབམའ])((\\u0F42)([\\u0F72\\u0F80]་?))>"r)
```

could be more accurate? Or maybe in some cases it's more likely to be a contraction ? wdyt?

**Comment by heacu** [comment]
i hate to be a pest @eroux  but would you mind puting each puzzlement in a different issue? otherwise it's difficult to keep track of what's been fixed and what hasn't.

**Comment by eroux** [comment]
sure
