### ISSUE TITLE
Old Tibetan: cleanup of two rules

### ISSUE THREAD

**Issue by eroux** [tibetan-nlp/tibcg3#5]
These two rules are pretty far apart in the file and that makes them almost look like a bug:

```
SUBSTITUTE ("ཅེད་པོ((འི|ར|ས)?་)"r) ("ཅེན་པོ$1"v) TARGET (σ);
...
SUBSTITUTE ("ཅེན་") ("ཆེན་") TARGET (σ) (1 ("(པོ|ཕོ)(འི|ས|ར)?་?"r));
```

Having the equivalent following one might be a bit less confusing although it does two different things at once:

```
SUBSTITUTE ("ཅེ(ད|ན)་(པོ|ཕོ)((འི|ར|ས)?་)"r) ("ཆེན་པོ$2"v) TARGET (σ);
```

**Comment by FChrispz** [comment]
Yes I agree, it's fine to have the two rules in one - we want to normalize everything to ཆེན་པོ
